name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to public_html
        run: rsync -av --exclude='.env' --exclude='.htaccess' --delete --progress ./ /home/saicelsl/public_html/ || true
