\name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Copy to public_html
        run: rsync -av --exclude='.env' --exclude='.htaccess' --progress ./ /home/saicelsl/public_html
