name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory to Laravel project
        run: cd /home/saicelsl/public_html
      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
