name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cache
        run: |
          cd /home/saicelsl/public_html
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
      - name: Deploy to cPanel
        uses: cpanel/cpanel-git-deploy@v2
        with:
          cpanel_host: ${{ secrets.CPANEL_HOST }}
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          cpanel_password: ${{ secrets.CPANEL_PASSWORD }}
          repository_path: /home/saicelsl/public_html
