// .github/workflows/laravel.yml

name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Copy to public_html
        run: |
          find . -type f ! -name ".env" ! -name ".htaccess" -exec rsync -avz --progress {} /home/saicelsl/public_html \;
